### PR TITLE
Fix division by zero panic in intervals

### PR DESCRIPTION
**Pull request by io12**
This fixes a panic that happens when calling `NextTime::next()` on `Interval` if the `Interval` is zero.

### CODE REVIEW

**Comment by io12** [comment]
Thanks for merging! Can you please make a new crates.io release so I can use the fix?

**Comment by mdsherry** [comment]
I'm working on that now. I did make a change: `0.days().next(&dt)` would return the start of the day, rather than acting as a no-op. Now any 0 interval should leave the datetime as it is.

**Comment by mdsherry** [comment]
[0.2.2 has been published](https://crates.io/crates/clokwerk)

**Comment by io12** [comment]
Thank you!

**Comment by mdsherry** [comment]
Thank you for finding the bug and sending a fix! I'm just sorry it took me a few days to get around to merging it

**Pull request merged**
